#############################################################################
# Makefile for building: itunesBackupParser.app/Contents/MacOS/itunesBackupParser
# Generated by qmake (3.0) (Qt 5.6.3)
# Project:  itunesBackupParser.pro
# Template: app
# Command: /Users/maxudin/Qt5.6.3/5.6.3/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile itunesBackupParser.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers -I../../../Qt5.6.3/5.6.3/clang_64/lib/QtGui.framework/Headers -I../../../Qt5.6.3/5.6.3/clang_64/lib/QtSql.framework/Headers -I../../../Qt5.6.3/5.6.3/clang_64/lib/QtNetwork.framework/Headers -I../../../Qt5.6.3/5.6.3/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../../Qt5.6.3/5.6.3/clang_64/mkspecs/macx-clang -F/Users/maxudin/Qt5.6.3/5.6.3/clang_64/lib
QMAKE         = /Users/maxudin/Qt5.6.3/5.6.3/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = itunesBackupParser1.0.0
DISTDIR = /Users/maxudin/Projects/QT-projects/iTunesParser/.tmp/itunesBackupParser1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/Users/maxudin/Qt5.6.3/5.6.3/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/maxudin/Qt5.6.3/5.6.3/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtSql -framework QtNetwork -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		instruction.cpp \
		TUpdater.cpp qrc_images.cpp \
		moc_mainwindow.cpp \
		moc_instruction.cpp
OBJECTS       = main.o \
		mainwindow.o \
		instruction.o \
		TUpdater.o \
		qrc_images.o \
		moc_mainwindow.o \
		moc_instruction.o
DIST          = ../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/qdevice.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/device_config.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/unix.conf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/mac.conf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/macx.conf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/clang.conf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/qconfig.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/default_post.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/qml_debug.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/qt.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/resources.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/moc.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/uic.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/yacc.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/lex.prf \
		itunesBackupParser.pro mainwindow.h \
		instruction.h \
		TUpdater.h \
		TConstants.h main.cpp \
		mainwindow.cpp \
		instruction.cpp \
		TUpdater.cpp
QMAKE_TARGET  = itunesBackupParser
DESTDIR       = 
TARGET        = itunesBackupParser.app/Contents/MacOS/itunesBackupParser


first: all
####### Build rules

$(TARGET): ui_mainwindow.h ui_instruction.h $(OBJECTS)  
	@test -d itunesBackupParser.app/Contents/MacOS/ || mkdir -p itunesBackupParser.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: itunesBackupParser.pro ../../../Qt5.6.3/5.6.3/clang_64/mkspecs/macx-clang/qmake.conf ../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/qdevice.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/device_config.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/unix.conf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/mac.conf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/macx.conf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/clang.conf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/qconfig.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/default_post.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/qml_debug.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/qt.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/resources.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/moc.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/uic.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/yacc.prf \
		../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/lex.prf \
		itunesBackupParser.pro \
		images.qrc \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtGui.framework/QtGui.prl \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtSql.framework/QtSql.prl \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile itunesBackupParser.pro
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/qdevice.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/device_config.prf:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/unix.conf:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/mac.conf:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/macx.conf:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/sanitize.conf:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/clang.conf:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/clang-mac.conf:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/qconfig.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_labscontrols_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_labstemplates_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/qt_config.prf:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/default_pre.prf:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/default_post.prf:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/qml_debug.prf:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/warn_on.prf:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/qt.prf:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/resources.prf:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/moc.prf:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/unix/opengl.prf:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/uic.prf:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/file_copies.prf:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/exceptions.prf:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/yacc.prf:
../../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/lex.prf:
itunesBackupParser.pro:
images.qrc:
../../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../../Qt5.6.3/5.6.3/clang_64/lib/QtGui.framework/QtGui.prl:
../../../Qt5.6.3/5.6.3/clang_64/lib/QtSql.framework/QtSql.prl:
../../../Qt5.6.3/5.6.3/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
../../../Qt5.6.3/5.6.3/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile itunesBackupParser.pro

qmake_all: FORCE

itunesBackupParser.app/Contents/PkgInfo: 
	@test -d itunesBackupParser.app/Contents || mkdir -p itunesBackupParser.app/Contents
	@$(DEL_FILE) itunesBackupParser.app/Contents/PkgInfo
	@echo "APPL????" > itunesBackupParser.app/Contents/PkgInfo
itunesBackupParser.app/Contents/Resources/empty.lproj: 
	@test -d itunesBackupParser.app/Contents/Resources || mkdir -p itunesBackupParser.app/Contents/Resources
	@touch itunesBackupParser.app/Contents/Resources/empty.lproj
	
itunesBackupParser.app/Contents/Info.plist: 
	@test -d itunesBackupParser.app/Contents || mkdir -p itunesBackupParser.app/Contents
	@$(DEL_FILE) itunesBackupParser.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,ru.xargon.itunesBackupParser,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,itunesBackupParser,g" -e "s,@LIBRARY@,itunesBackupParser,g" -e "s,@TYPEINFO@,????,g" ../../../Qt5.6.3/5.6.3/clang_64/mkspecs/macx-clang/Info.plist.app >itunesBackupParser.app/Contents/Info.plist

all: Makefile \
		itunesBackupParser.app/Contents/PkgInfo \
		itunesBackupParser.app/Contents/Resources/empty.lproj \
		itunesBackupParser.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents images.qrc $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h instruction.h TUpdater.h TConstants.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp instruction.cpp TUpdater.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui instruction.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r itunesBackupParser.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_images.cpp
qrc_images.cpp: images.qrc \
		screen/IMG_0270.PNG \
		screen/IMG_0274.PNG \
		screen/IMG_0278.PNG \
		screen/IMG_0269.PNG \
		screen/IMG_0273.PNG \
		screen/IMG_0277.PNG \
		screen/IMG_0272.PNG \
		screen/IMG_0276.PNG \
		screen/IMG_0271.PNG \
		screen/IMG_0275.PNG
	/Users/maxudin/Qt5.6.3/5.6.3/clang_64/bin/rcc -name images images.qrc -o qrc_images.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_instruction.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_instruction.cpp
moc_mainwindow.cpp: ../../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtNetwork.framework/Headers/QNetworkRequest \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtNetwork.framework/Headers/qnetworkrequest.h \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtNetwork.framework/Headers/QHttpMultiPart \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtNetwork.framework/Headers/qhttpmultipart.h \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtNetwork.framework/Headers/QNetworkReply \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtNetwork.framework/Headers/qnetworkreply.h \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QTextBrowser \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		instruction.h \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		TUpdater.h \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtCore.framework/Headers/qobject.h \
		TConstants.h \
		mainwindow.h
	/Users/maxudin/Qt5.6.3/5.6.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/maxudin/Qt5.6.3/5.6.3/clang_64/mkspecs/macx-clang -I/Users/maxudin/Projects/QT-projects/iTunesParser -I/Users/maxudin/Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/maxudin/Qt5.6.3/5.6.3/clang_64/lib/QtGui.framework/Headers -I/Users/maxudin/Qt5.6.3/5.6.3/clang_64/lib/QtSql.framework/Headers -I/Users/maxudin/Qt5.6.3/5.6.3/clang_64/lib/QtNetwork.framework/Headers -I/Users/maxudin/Qt5.6.3/5.6.3/clang_64/lib/QtCore.framework/Headers -F/Users/maxudin/Qt5.6.3/5.6.3/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

moc_instruction.cpp: ../../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		instruction.h
	/Users/maxudin/Qt5.6.3/5.6.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/maxudin/Qt5.6.3/5.6.3/clang_64/mkspecs/macx-clang -I/Users/maxudin/Projects/QT-projects/iTunesParser -I/Users/maxudin/Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/maxudin/Qt5.6.3/5.6.3/clang_64/lib/QtGui.framework/Headers -I/Users/maxudin/Qt5.6.3/5.6.3/clang_64/lib/QtSql.framework/Headers -I/Users/maxudin/Qt5.6.3/5.6.3/clang_64/lib/QtNetwork.framework/Headers -I/Users/maxudin/Qt5.6.3/5.6.3/clang_64/lib/QtCore.framework/Headers -F/Users/maxudin/Qt5.6.3/5.6.3/clang_64/lib instruction.h -o moc_instruction.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_instruction.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_instruction.h
ui_mainwindow.h: mainwindow.ui
	/Users/maxudin/Qt5.6.3/5.6.3/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_instruction.h: instruction.ui
	/Users/maxudin/Qt5.6.3/5.6.3/clang_64/bin/uic instruction.ui -o ui_instruction.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtNetwork.framework/Headers/QNetworkRequest \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtNetwork.framework/Headers/qnetworkrequest.h \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtNetwork.framework/Headers/QHttpMultiPart \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtNetwork.framework/Headers/qhttpmultipart.h \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtNetwork.framework/Headers/QNetworkReply \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtNetwork.framework/Headers/qnetworkreply.h \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QTextBrowser \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		instruction.h \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		TUpdater.h \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtCore.framework/Headers/qobject.h \
		TConstants.h \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtNetwork.framework/Headers/QNetworkRequest \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtNetwork.framework/Headers/qnetworkrequest.h \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtNetwork.framework/Headers/QHttpMultiPart \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtNetwork.framework/Headers/qhttpmultipart.h \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtNetwork.framework/Headers/QNetworkReply \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtNetwork.framework/Headers/qnetworkreply.h \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QTextBrowser \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		instruction.h \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		TUpdater.h \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtCore.framework/Headers/qobject.h \
		TConstants.h \
		ui_mainwindow.h \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtCore.framework/Headers/QDir \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

instruction.o: instruction.cpp instruction.h \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		ui_instruction.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o instruction.o instruction.cpp

TUpdater.o: TUpdater.cpp TUpdater.h \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtCore.framework/Headers/qobject.h \
		TConstants.h \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtNetwork.framework/Headers/QNetworkRequest \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtNetwork.framework/Headers/qnetworkrequest.h \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtNetwork.framework/Headers/QNetworkReply \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtNetwork.framework/Headers/qnetworkreply.h \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtCore.framework/Headers/QDir \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtCore.framework/Headers/QFile \
		../../../Qt5.6.3/5.6.3/clang_64/lib/QtCore.framework/Headers/qfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TUpdater.o TUpdater.cpp

qrc_images.o: qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_images.o qrc_images.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_instruction.o: moc_instruction.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_instruction.o moc_instruction.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

